---
## https://docs.travis-ci.com/user/osx-ci-environment/
os:
  - osx

#language: python
#python: "2.7"
before_install:
  - ln -s ansible-macos-apps-install ../juju4.macos-apps-install
  - sw_vers
  - uname -a
  - python --version
  - brew update
  - brew install libidn2
  - brew install openssl
  - brew upgrade openssl
  - brew install python3
  - brew doctor
  - python --version
#  - pip --version
  - python -c "import ssl; print(ssl.OPENSSL_VERSION)"
  - python3 --version
  - python3 -c "import ssl; print(ssl.OPENSSL_VERSION)"
  - pip3 --version
#  - which pip
## error: could not create '/Library/Python/2.7/site-packages/ansible': Permission denied
#  - pip install ansible ansible-lint
#  - pip install --user ansible ansible-lint
  - env
  - find . -ls
#  - find $HOME/Library $HOME/.local -ls || true
install:
#  - brew install ansible
  - python2 -c "import ssl; print(ssl.OPENSSL_VERSION)"
  - python2 -c 'import ssl; ssl.PROTOCOL_TLSv1_2'
  - pip3 install ansible
  - python3 -c 'import ssl; ssl.PROTOCOL_TLSv1_2'
  - ansible --version
  - "{ echo '[defaults]'; echo 'roles_path = ../'; } >> ansible.cfg"
script:
  - "echo \"[test-kitchen]\nlocalhost\" > inventory"

#  - "ansible-lint tasks/main.yml"

# Check the role/playbook's syntax.
  - "ansible-playbook -i inventory --syntax-check test/integration/default/default.yml"

# Run the role/playbook with ansible-playbook.
  - "ansible-playbook -i inventory --connection=local --sudo -vvvv test/integration/default/default.yml -vv"

# Run the role/playbook again, checking to make sure it's idempotent.
## FIXME! known fail
  - "ansible-playbook -i inventory test/integration/default/default.yml --connection=local --sudo | tee /tmp/idempotency.log | grep -q 'changed=0.*failed=0'  && (echo 'Idempotence test: pass' && exit 0)  || (echo 'Idempotence test: fail' && cat /tmp/idempotency.log && exit 0)"

  - "ls -lh /Applications/"
