---
## https://docs.travis-ci.com/user/osx-ci-environment/
os:
  - osx

osx_image:
# OS X 10.15
  - xcode12
# OS X 10.14
  - xcode11.2
# OS X 10.13
  - xcode10.1
# OS X 10.12
#  - xcode9.2

env:
  matrix:
    - suite='default'
    - suite='default-target-user'

#language: python
#python: "2.7"
before_install:
  - ln -s ansible-macos-apps-install ../juju4.macos_apps_install
  - sw_vers
  - uname -a
  - python --version
  - brew update
  - brew install libidn2 || brew upgrade libidn2
  - brew install openssl
  - brew outdated
# xcode9.2: force python upgrade...
  - if (brew outdated | grep python > /dev/null); then brew upgrade python@3.8 || brew link --overwrite python; fi
  - if (brew outdated | grep openssl > /dev/null); then brew upgrade openssl || true; fi
  - brew ls --verbose openssl
  - brew update
  - brew doctor || true
  - python --version
#  - pip --version
  - python -c "import ssl; print(ssl.OPENSSL_VERSION)"
  - python3 --version
  - python3 -c "import ssl; print(ssl.OPENSSL_VERSION)"
  - pip3 --version
#  - which pip
  - env
  - find . -ls
#  - find $HOME/Library $HOME/.local -ls || true

install:
#  - brew install ansible
  - python -c 'import ssl; ssl.PROTOCOL_TLSv1_2' || true
  - pip3 install ansible==2.9.11
  - pip3 install ansible-lint
  - python3 -c 'import ssl; ssl.PROTOCOL_TLSv1_2'
  - ansible --version
  - which ansible
  - "{ echo '[defaults]'; echo 'roles_path = ../'; } >> ansible.cfg"
script:
  - "echo \"localhost\" > inventory"

  - "ansible-lint tasks/main.yml || true"

# Check the role/playbook's syntax.
  - "ansible-playbook -i inventory --syntax-check test/integration/${suite}/default.yml"

# Run the role/playbook with ansible-playbook.
  - "ansible-playbook -i inventory --connection=local --become -vvvv test/integration/${suite}/default.yml"

# Run the role/playbook again, checking to make sure it's idempotent.
## FIXME! known fail
  - "ansible-playbook -i inventory test/integration/${suite}/default.yml --connection=local --become | tee /tmp/idempotency.log | grep -q 'changed=0.*failed=0'  && (echo 'Idempotence test: pass' && exit 0)  || (echo 'Idempotence test: fail' && cat /tmp/idempotency.log && exit 0)"

after_script:
  - "ls -lA /Users/travis/"
  - "ls -lA /Users/travis/Downloads/"
  - "ls -lh /Applications/"
  - "ls -lh /usr/local/bin/"
  - "find /usr /opt -iname inspec"
